top_srcdir   = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache
top_builddir = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache
srcdir       = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/modules/metadata
builddir     = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/modules/metadata
VPATH        = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/modules/metadata

include $(top_srcdir)/build/special.mk

