top_srcdir   = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache
top_builddir = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache
srcdir       = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/server/mpm/event
builddir     = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/server/mpm/event
VPATH        = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/server/mpm/event
include $(top_srcdir)/build/special.mk
