#!/bin/bash

bin/dbench $@ -c client.txt
numberOfProcesses=`ps -aux | grep "dbench" | wc -l`
if [ $numberOfProcesses -gt 1 ]; then
    kill -9 `ps -aux | grep "dbench" | head -1 | awk '{print \$2}'`
fi