#!/bin/bash

argumentType=`echo $1 | awk -F"_" '{print $2}'`
testType=`echo $1 | awk -F"_" '{print $1}'`

case ${argumentType} in
	("int") argumentType=3 ;;
	("float") argumentType=6 ;;
	(*) echo "Not valid option" ;;
esac

for i in {1..10}; do
	./ramsmp -b ${argumentType} -l ${testType} 
done
