top_srcdir   = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache
top_builddir = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache
srcdir       = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/modules/cache
builddir     = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/modules/cache
VPATH        = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/modules/cache

include $(top_srcdir)/build/special.mk

