top_srcdir   = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache
top_builddir = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache
srcdir       = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/os
builddir     = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/os
VPATH        = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/os

SUBDIRS = $(OS_DIR)

include $(top_builddir)/build/rules.mk
