top_srcdir   = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache
top_builddir = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache
srcdir       = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/modules/mappers
builddir     = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/modules/mappers
VPATH        = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/modules/mappers

include $(top_srcdir)/build/special.mk

