top_srcdir   = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache
top_builddir = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache
srcdir       = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/modules/proxy/balancers
builddir     = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/modules/proxy/balancers
VPATH        = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/modules/proxy/balancers
# a modules Makefile has no explicit targets -- they will be defined by
# whatever modules are enabled. just grab special.mk to deal with this.
include $(top_srcdir)/build/special.mk
