# Last modification: 2007-08-27 09:34:42

install:
	@echo "Copying script to /usr/local/bin"
	@cp sudokut /usr/local/bin
	@echo "Copying man page to /usr/local/man/man1"
	if ! [ -e /usr/local/man/man1 ] ; then mkdir -p /usr/local/man/man1; fi
	@cp sudokut.1 /usr/local/man/man1
