top_srcdir   = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache
top_builddir = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache
srcdir       = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/modules/filters
builddir     = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/modules/filters
VPATH        = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/modules/filters

include $(top_srcdir)/build/special.mk

