top_srcdir   = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache
top_builddir = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache
srcdir       = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/modules/core
builddir     = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/modules/core
VPATH        = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/modules/core

include $(top_srcdir)/build/special.mk

