top_srcdir   = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache
top_builddir = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache
srcdir       = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/os/unix
builddir     = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/os/unix
VPATH        = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/os/unix

LTLIBRARY_NAME    = libos.la
LTLIBRARY_SOURCES = unixd.c

include $(top_srcdir)/build/ltlib.mk
