top_srcdir   = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache
top_builddir = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache
srcdir       = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/modules/echo
builddir     = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/modules/echo
VPATH        = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/modules/echo

include $(top_srcdir)/build/special.mk

