#!/bin/sh

# set frequency range parameters
freqstart=1000000000
freqstep=1500000
freqend=3000000000

frequency=$freqstart

# backup old sweeps
mv fields_in.dat fields_in.old
mv fields_sc.dat fields_sc.old
mv frequency.dat frequency.old

while [ $frequency -le $freqend ]
do
        ./nero2d case.igf FREQUENCY $frequency
	echo "$frequency " >> frequency.dat
	cat circle0_in.cdf >> fields_in.dat
	cat circle0_sc.cdf >> fields_sc.dat
        frequency=`expr $frequency + $freqstep`
done

# clean up temp files
rm -f circle0_in.cdf
rm -f circle0_sc.cdf
