top_srcdir   = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache
top_builddir = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache
srcdir       = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/srclib
builddir     = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/srclib
VPATH        = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/srclib

BUILD_SUBDIRS = $(AP_BUILD_SRCLIB_DIRS)
CLEAN_SUBDIRS = $(AP_CLEAN_SRCLIB_DIRS)

include $(top_builddir)/build/rules.mk
