top_srcdir   = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache
top_builddir = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache
srcdir       = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/server/mpm
builddir     = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/server/mpm
VPATH        = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/server/mpm

SUBDIRS = $(MPM_SUBDIRS)

include $(top_builddir)/build/rules.mk
