top_srcdir   = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache
top_builddir = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache
srcdir       = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/modules/http
builddir     = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/modules/http
VPATH        = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/modules/http

include $(top_srcdir)/build/special.mk

