top_srcdir   = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache
top_builddir = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache
srcdir       = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/modules/loggers
builddir     = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/modules/loggers
VPATH        = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/modules/loggers

include $(top_srcdir)/build/special.mk

