top_srcdir   = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache
top_builddir = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache
srcdir       = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/modules/aaa
builddir     = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/modules/aaa
VPATH        = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/modules/aaa

include $(top_srcdir)/build/special.mk

