top_srcdir   = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache
top_builddir = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache
srcdir       = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/modules/generators
builddir     = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/modules/generators
VPATH        = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/modules/generators

include $(top_srcdir)/build/special.mk

