top_srcdir   = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache
top_builddir = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache
srcdir       = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/modules/arch/unix
builddir     = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/modules/arch/unix
VPATH        = /home/sgeorgiou/GitHub/phoronixDataSet/tasks/apache/modules/arch/unix

include $(top_srcdir)/build/special.mk

